// Research Workflow Types
// Defines the structure for the end-to-end research workflow

export type WorkflowPhase = 
  | "research-question"
  | "exploratory-review"
  | "systematic-review"
  | "literature-synthesis"
  | "rationale"
  | "study-design"
  | "sample-size"
  | "statistical-plan"
  | "methods"
  | "timeline-ethics"
  | "proposal";

export interface ResearchQuestion {
  population: string;
  intervention?: string;
  exposure?: string;
  comparison?: string;
  outcome: string;
  studyType: "interventional" | "observational" | "diagnostic" | "prognostic";
  picoSummary?: string;
  refinementNotes?: string;
}

export interface ExploratoryReview {
  keywords: string[];
  initialSearches: Array<{
    query: string;
    resultsCount: number;
    date: string;
  }>;
  keyPapers: Array<{
    pmid: string;
    title: string;
    authors: string;
    year: string;
    relevance: string;
  }>;
  knowledgeGaps?: string[];
}

export interface SystematicReview {
  searchStrategy: string;
  databases: string[];
  inclusionCriteria: string[];
  exclusionCriteria: string[];
  includedPapers: Array<{
    pmid: string;
    title: string;
    authors: string;
    year: string;
    abstract?: string;
    reason?: string;
  }>;
  excludedPapers: Array<{
    pmid: string;
    title: string;
    reason: string;
  }>;
  prismaFlow?: {
    identified: number;
    screened: number;
    eligible: number;
    included: number;
  };
}

export interface LiteratureSynthesis {
  themes: Array<{
    name: string;
    description: string;
    paperCount: number;
    keyFindings: string[];
  }>;
  evidenceTable: Array<{
    study: string;
    design: string;
    sampleSize: number;
    findings: string;
    quality: "high" | "moderate" | "low";
  }>;
  evidenceGaps: string[];
  conflictingFindings?: string[];
  consensusPoints?: string[];
}

export interface Rationale {
  significance: string;
  novelty: string;
  clinicalImpact?: string;
  theoreticalContribution?: string;
  feasibility: string;
  expectedOutcomes: string;
}

export interface StudyDesign {
  designType: string;
  setting: string;
  population: string;
  samplingMethod: string;
  interventionDetails?: string;
  controlGroup?: string;
  blinding?: string;
  randomization?: string;
  timeline: string;
}

export interface SampleSizeCalculation {
  testType: string;
  parameters: Record<string, number>;
  result: {
    sampleSize: number;
    perGroup?: number;
    totalSampleSize: number;
  };
  justification: string;
  feasibilityCheck?: string;
}

export interface StatisticalPlan {
  primaryOutcome: string;
  primaryAnalysis: string;
  secondaryOutcomes: string[];
  secondaryAnalyses: string[];
  subgroupAnalyses?: string[];
  sensitivityAnalyses?: string[];
  missingDataStrategy: string;
  softwarePackages: string[];
}

export interface Methods {
  dataCollection: {
    methods: string[];
    instruments: string[];
    frequency: string;
    duration: string;
  };
  procedures: {
    screening: string;
    enrollment: string;
    intervention?: string;
    followUp: string;
  };
  qualityControl: string[];
  dataManagement: string;
  ethics: {
    informedConsent: string;
    confidentiality: string;
    dataProtection: string;
  };
}

export interface TimelineEthics {
  phases: Array<{
    name: string;
    duration: string;
    startMonth: number;
    endMonth: number;
    milestones: string[];
  }>;
  totalDuration: string;
  ethicsApproval: {
    required: boolean;
    institution?: string;
    documents?: string[];
    status?: "not-started" | "in-progress" | "submitted" | "approved";
  };
  regulatoryApprovals?: string[];
}

export interface ProposalGeneration {
  template: "imrad" | "grant" | "thesis" | "custom";
  sections: {
    title?: string;
    abstract?: string;
    introduction?: string;
    methods?: string;
    expectedResults?: string;
    discussion?: string;
    references?: string;
    budget?: string;
    timeline?: string;
  };
  autoGenerated: boolean;
  lastUpdated: string;
}

// Main workflow state interface
export interface ResearchWorkflowState {
  id?: number;
  userId?: number;
  projectId?: number;
  
  currentPhase: number;
  completedPhases: number[];
  
  researchQuestion?: ResearchQuestion;
  exploratoryReview?: ExploratoryReview;
  systematicReview?: SystematicReview;
  literatureSynthesis?: LiteratureSynthesis;
  rationale?: Rationale;
  studyDesign?: StudyDesign;
  sampleSize?: SampleSizeCalculation;
  statisticalPlan?: StatisticalPlan;
  methods?: Methods;
  timelineEthics?: TimelineEthics;
  proposal?: ProposalGeneration;
  
  createdAt?: string;
  updatedAt?: string;
}

// Type for creating a new workflow
export type CreateWorkflowInput = Omit<ResearchWorkflowState, "id" | "createdAt" | "updatedAt">;

// Type for updating a workflow
export type UpdateWorkflowInput = Partial<ResearchWorkflowState> & { id: number };
